name: Bot to Respond to Issues

on:
  issues:
    types: [opened]

jobs:
  respond_to_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Send a response to the issue
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"body": "Thank you for opening an issue. We will look into it!"}' \
        https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments
