name: Create Landing Page Issue

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually
  schedule:
    - cron: '0 9 * * 1'  # Schedule to trigger every Monday at 9 AM

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create a new issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Landing Page Improvement'
          content-filepath: '.github/ISSUE_TEMPLATE/landing-page.md'
          labels: 'enhancement, landing-page'
